services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: .env
    volumes:
      - ./config:/app/config
      - ./icons:/app/public/icons
      # - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    environment:
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_ALLOWED_HOSTS: "localhost:3000,10.42.42.7:3000,homepage.local.turtletough.net"
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.local.turtletough.net`)"
      - "traefik.http.routers.homepage.entrypoints=https"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

networks:
  proxy:
    external: true
