services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /home/serveradmin/homepage/config:/app/config
      - /home/serveradmin/homepage/icons:/app/public/icons
      # - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    environment:
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_ALLOWED_HOSTS: "localhost:3000,10.42.42.7:3000,homepage.local.turtletough.net"
      # PiHole
      HOMEPAGE_VAR_PIHOLE_URL_1: ${HOMEPAGE_VAR_PIHOLE_URL_1}
      HOMEPAGE_VAR_PIHOLE_URL_1_des: ${HOMEPAGE_VAR_PIHOLE_URL_1_des}
      HOMEPAGE_VAR_PIHOLE_URL_2: ${HOMEPAGE_VAR_PIHOLE_URL_2}
      HOMEPAGE_VAR_PIHOLE_URL_2_des: ${HOMEPAGE_VAR_PIHOLE_URL_2_des}
    
      # Proxmox 2
      HOMEPAGE_VAR_PROXMOX_2_URL: ${HOMEPAGE_VAR_PROXMOX_2_URL}
      HOMEPAGE_VAR_PROXMOX_2_URL_des: ${HOMEPAGE_VAR_PROXMOX_2_URL_des}
      HOMEPAGE_VAR_PROXMOX_USER: ${HOMEPAGE_VAR_PROXMOX_USER}
      HOMEPAGE_VAR_PROXMOX_API_KEY: ${HOMEPAGE_VAR_PROXMOX_API_KEY}
    
      # Proxmox 3
      HOMEPAGE_VAR_PROXMOX_3_URL: ${HOMEPAGE_VAR_PROXMOX_3_URL}
      HOMEPAGE_VAR_PROXMOX_3_URL_des: ${HOMEPAGE_VAR_PROXMOX_3_URL_des}
    
      # Portainer
      HOMEPAGE_VAR_PORTAINER_URL: ${HOMEPAGE_VAR_PORTAINER_URL}
      HOMEPAGE_VAR_PORTAINER_URL_des: ${HOMEPAGE_VAR_PORTAINER_URL_des}
    
      # OPNSense
      HOMEPAGE_VAR_OPNSENSE_NETWORK_URL: ${HOMEPAGE_VAR_OPNSENSE_NETWORK_URL}
      HOMEPAGE_VAR_OPNSENSE_NETWORK_URL_des: ${HOMEPAGE_VAR_OPNSENSE_NETWORK_URL_des}
      HOMEPAGE_VAR_OPNSENSE_USERNAME: ${HOMEPAGE_VAR_OPNSENSE_USERNAME}
      HOMEPAGE_VAR_OPNSENSE_PASSWORD: ${HOMEPAGE_VAR_OPNSENSE_PASSWORD}
    
      # Uptime Kuma
      HOMEPAGE_VAR_UPTIME_KUMA_URL: ${HOMEPAGE_VAR_UPTIME_KUMA_URL}
      HOMEPAGE_VAR_UPTIME_KUMA_URL_des: ${HOMEPAGE_VAR_UPTIME_KUMA_URL_des}
      HOMEPAGE_VAR_UPTIME_KUMA_API_KEY: ${HOMEPAGE_VAR_UPTIME_KUMA_API_KEY}
    
      # TrueNAS
      HOMEPAGE_VAR_TRUENAS_URL: ${HOMEPAGE_VAR_TRUENAS_URL}
      HOMEPAGE_VAR_TRUENAS_URL_des: ${HOMEPAGE_VAR_TRUENAS_URL_des}
      HOMEPAGE_VAR_TRUENAS_API_KEY: ${HOMEPAGE_VAR_TRUENAS_API_KEY}
    
      # Plex
      HOMEPAGE_VAR_PLEX_URL: ${HOMEPAGE_VAR_PLEX_URL}
      HOMEPAGE_VAR_PLEX_URL_des: ${HOMEPAGE_VAR_PLEX_URL_des}
      HOMEPAGE_VAR_PLEX_API_TOKEN: ${HOMEPAGE_VAR_PLEX_API_TOKEN}
    
      # HDHomerun
      HOMEPAGE_VAR_HDHOMERUN_URL: ${HOMEPAGE_VAR_HDHOMERUN_URL}
      HOMEPAGE_VAR_HDHOMERUN_URL_des: ${HOMEPAGE_VAR_HDHOMERUN_URL_des}
    
      # Home Assistant
      HOMEPAGE_VAR_HOME_ASSISTANT_URL: ${HOMEPAGE_VAR_HOME_ASSISTANT_URL}
      HOMEPAGE_VAR_HOME_ASSISTANT_URL_des: ${HOMEPAGE_VAR_HOME_ASSISTANT_URL_des}
      HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY: ${HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}
    
      # qBittorrent
      HOMEPAGE_VAR_QBITTORRENT_URL: ${HOMEPAGE_VAR_QBITTORRENT_URL}
      HOMEPAGE_VAR_QBITTORRENT_URL_des: ${HOMEPAGE_VAR_QBITTORRENT_URL_des}
      HOMEPAGE_VAR_QBITTORRENT_USER: ${HOMEPAGE_VAR_QBITTORRENT_USER}
      HOMEPAGE_VAR_QBITTORRENT_PASS: ${HOMEPAGE_VAR_QBITTORRENT_PASS}
    
      # Traefik
      HOMEPAGE_VAR_TRAEFIK_URL: ${HOMEPAGE_VAR_TRAEFIK_URL}
      HOMEPAGE_VAR_TRAEFIK_URL_des: ${HOMEPAGE_VAR_TRAEFIK_URL_des}
      HOMEPAGE_VAR_TRAEFIK_USER: ${HOMEPAGE_VAR_TRAEFIK_USER}
      HOMEPAGE_VAR_TRAEFIK_PASS: ${HOMEPAGE_VAR_TRAEFIK_PASS}
    
      # Switches
      HOMEPAGE_VAR_SWITCH0_NETWORK_URL: ${HOMEPAGE_VAR_SWITCH0_NETWORK_URL}
      HOMEPAGE_VAR_SWITCH0_NETWORK_URL_des: ${HOMEPAGE_VAR_SWITCH0_NETWORK_URL_des}
    
      HOMEPAGE_VAR_SWITCH1_NETWORK_URL: ${HOMEPAGE_VAR_SWITCH1_NETWORK_URL}
      HOMEPAGE_VAR_SWITCH1_NETWORK_URL_des: ${HOMEPAGE_VAR_SWITCH1_NETWORK_URL_des}
    
      HOMEPAGE_VAR_SWITCH2_NETWORK_URL: ${HOMEPAGE_VAR_SWITCH2_NETWORK_URL}
      HOMEPAGE_VAR_SWITCH2_NETWORK_URL_des: ${HOMEPAGE_VAR_SWITCH2_NETWORK_URL_des}
    
      # TP-Link
      HOMEPAGE_VAR_TP-LINK_B95_URL: ${HOMEPAGE_VAR_TP-LINK_B95_URL}
      HOMEPAGE_VAR_TP-LINK_B95_URL_des: ${HOMEPAGE_VAR_TP-LINK_B95_URL_des}
    
      # Jellyfin
      HOMEPAGE_VAR_JELLYFIN_URL: ${HOMEPAGE_VAR_JELLYFIN_URL}
      HOMEPAGE_VAR_JELLYFIN_URL_des: ${HOMEPAGE_VAR_JELLYFIN_URL_des}
      HOMEPAGE_VAR_JELLYFIN_API_KEY: ${HOMEPAGE_VAR_JELLYFIN_API_KEY}
    
      # Storyteller
      HOMEPAGE_VAR_STORYTELLER_URL: ${HOMEPAGE_VAR_STORYTELLER_URL}
      HOMEPAGE_VAR_STORYTELLER_URL_des: ${HOMEPAGE_VAR_STORYTELLER_URL_des}
    
      # Paperless
      HOMEPAGE_VAR_PAPERLESS_URL: ${HOMEPAGE_VAR_PAPERLESS_URL}
      HOMEPAGE_VAR_PAPERLESS_URL_des: ${HOMEPAGE_VAR_PAPERLESS_URL_des}
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.local.turtletough.net`)"
      - "traefik.http.routers.homepage.entrypoints=https"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

networks:
  proxy:
    external: true
